FROM node:14-slim

#docker-compose up -d --build --force-recreate --no-deps && lazydocker

RUN apt-get update && apt-get install -yq curl git  g++ python make mc screen nano


RUN git clone -b main https://github.com/shubham-laware/Aczen.git /root/MultiCurrencyWallet

WORKDIR /root/MultiCurrencyWallet

RUN npm i

CMD [ "npm", "run","dev" ]

EXPOSE 9001

